name: Daily Shorts (all channels)

on:
  schedule:
    # US/Eastern 12:30 & 20:30 için hem EDT (UTC-4) hem EST (UTC-5) slotları.
    # Gate job yanlış slotları kapatır, böylece çift çalışmaz.
    - cron: "30 16 * * *"  # 12:30 ET (EDT dönemi)
    - cron: "30 0 * * *"   # 20:30 ET (EDT dönemi)
    - cron: "30 17 * * *"  # 12:30 ET (EST dönemi)
    - cron: "30 1 * * *"   # 20:30 ET (EST dönemi)
  workflow_dispatch: {}

permissions:
  contents: read
  actions: read
  checks: read
  id-token: none

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  # ---- Time gate: sadece US/Eastern 12:30 veya 20:30 ise devam ----
  time-gate:
    runs-on: ubuntu-latest
    outputs:
      should_run: ${{ steps.chk.outputs.should_run }}
    steps:
      - name: Check US/Eastern time window
        id: chk
        shell: bash
        run: |
          set -euo pipefail
          ET_NOW=$(TZ=America/New_York date +'%H:%M')
          echo "US/Eastern now: ${ET_NOW}"
          if [ "$ET_NOW" = "12:30" ] || [ "$ET_NOW" = "20:30" ]; then
            echo "should_run=true" >> "$GITHUB_OUTPUT"
          else
            echo "should_run=false" >> "$GITHUB_OUTPUT"
          fi

  make-matrix:
    runs-on: ubuntu-latest
    needs: time-gate
    if: ${{ needs.time-gate.outputs.should_run == 'true' || github.event_name == 'workflow_dispatch' }}
    outputs:
      matrix: ${{ steps.mk.outputs.matrix }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build matrix from channels.yml (no ::set-output)
        id: mk
        shell: bash
        run: |
          python - <<'PY'
          import yaml, json
          data = yaml.safe_load(open("channels.yml","r",encoding="utf-8")) or {}
          chs = []
          for ch in data.get("channels", []):
              chs.append({
                  "name": ch.get("name"),
                  "env": ch.get("env", ch.get("name")),
                  "mode": ch.get("mode","freeform"),
                  "lang": ch.get("lang","en"),
                  "visibility": ch.get("visibility","public"),
                  "seed": ch.get("seed","0"),
              })
          open("mx.json","w",encoding="utf-8").write(json.dumps({"include": chs}))
          PY
          echo "matrix=$(cat mx.json)" >> "$GITHUB_OUTPUT"

  build-upload:
    needs: [make-matrix, time-gate]
    if: ${{ needs.time-gate.outputs.should_run == 'true' || github.event_name == 'workflow_dispatch' }}
    runs-on: ubuntu-latest
    timeout-minutes: 60
    strategy:
      fail-fast: false
      max-parallel: 6
      matrix: ${{ fromJSON(needs.make-matrix.outputs.matrix) }}

    environment: ${{ matrix.env }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: (Optional) Fetch LFS assets (e.g., bgm/)
        run: |
          if command -v git >/dev/null 2>&1; then
            if git lfs version >/dev/null 2>&1; then git lfs pull || true; fi
          fi
          ls -la bgm || true

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: "pip"
          cache-dependency-path: requirements.txt

      - name: Setup FFmpeg (fast + cached)
        uses: FedericoCarboni/setup-ffmpeg@v3
        with:
          ffmpeg-version: release

      - name: Restore global state cache
        uses: actions/cache/restore@v4
        with:
          path: |
            state_global.json
            state_global_topics.json
          key: global-state-${{ github.run_id }}
          restore-keys: |
            global-state-

      - name: Restore channel state cache
        uses: actions/cache/restore@v4
        with:
          path: state_${{ matrix.name }}.json
          key: chstate-${{ matrix.name }}-${{ github.run_id }}
          restore-keys: |
            chstate-${{ matrix.name }}-

      # ---------- SAFE ENV EXPORT ----------
      - name: Export channel variables (safe)
        shell: bash
        env:
          MATRIX_NAME:           ${{ matrix.name }}
          DEFAULT_LANG:          ${{ matrix.lang }}
          DEFAULT_MODE:          ${{ matrix.mode }}
          DEFAULT_VISIBILITY:    ${{ matrix.visibility }}
          DEFAULT_SEED:          ${{ matrix.seed }}

          VARS_TOPIC:            ${{ vars.TOPIC }}
          VARS_LANG:             ${{ vars.LANG }}
          VARS_MODE:             ${{ vars.MODE }}
          VARS_VISIBILITY:       ${{ vars.VISIBILITY }}
          VARS_ROTATION_SEED:    ${{ vars.ROTATION_SEED }}
          VARS_SEARCH_TERMS:     ${{ vars.SEARCH_TERMS }}
          VARS_GEMINI_PROMPT:    ${{ vars.GEMINI_PROMPT }}
          VARS_TTS_RATE:         ${{ vars.TTS_RATE }}
          VARS_TTS_VOICE:        ${{ vars.TTS_VOICE }}

          # karaoke timing
          KARAOKE_OFFSET_MS: "-200"
          KARAOKE_SPEED: "1.35"
        run: |
          set -euo pipefail

          CHANNEL_NAME="$MATRIX_NAME"
          LANG_VAL="${VARS_LANG:-$DEFAULT_LANG}"
          MODE_VAL="${VARS_MODE:-$DEFAULT_MODE}"
          VIS_VAL="${VARS_VISIBILITY:-$DEFAULT_VISIBILITY}"
          SEED_VAL="${VARS_ROTATION_SEED:-$DEFAULT_SEED}"

          wenv () {
            local __name="$1"; shift
            local __val="$*"
            local __delim="EOF_${__name}_$$"
            {
              echo "${__name}<<${__delim}"
              printf '%s\n' "${__val}"
              echo "${__delim}"
            } >> "$GITHUB_ENV"
          }

          wenv CHANNEL_NAME        "${CHANNEL_NAME}"
          wenv TOPIC               "${VARS_TOPIC}"
          wenv LANG                "${LANG_VAL}"
          wenv MODE                "${MODE_VAL}"
          wenv VISIBILITY          "${VIS_VAL:-public}"
          wenv ROTATION_SEED       "${SEED_VAL}"
          wenv SEARCH_TERMS        "${VARS_SEARCH_TERMS}"
          wenv GEMINI_PROMPT       "${VARS_GEMINI_PROMPT}"
          wenv TTS_RATE            "${VARS_TTS_RATE}"
          wenv TTS_VOICE           "${VARS_TTS_VOICE}"
          wenv UPLOAD_TO_YT        "1"

      - name: Install deps
        run: |
          python -m pip install -U pip
          pip install -r requirements.txt

      - name: Build video
        env:
          GEMINI_API_KEY:   ${{ secrets.GEMINI_API_KEY }}
          PEXELS_API_KEY:   ${{ secrets.PEXELS_API_KEY }}
          YT_CLIENT_ID:     ${{ secrets.YT_CLIENT_ID }}
          YT_CLIENT_SECRET: ${{ secrets.YT_CLIENT_SECRET }}
          YT_REFRESH_TOKEN: ${{ secrets.YT_REFRESH_TOKEN }}

          REQUIRE_CAPTIONS: "1"
          KARAOKE_CAPTIONS: "1"
          CAPTIONS_UPPER:   "1"
          KARAOKE_MODE:     "fill"
          KARAOKE_INACTIVE: "#FFD700"
          KARAOKE_ACTIVE:   "#3EA6FF"
          KARAOKE_OUTLINE:  "#000000"

          # ==== CAPTION SYNC TWEAKS ====
          KARAOKE_SPEEDUP_PCT:  "5.0"
          KARAOKE_RAMP_PCT:     "2.0"
          KARAOKE_EARLY_END_MS: "120"
          CAPTION_LEAD_MS:      "80"

          # ==== BGM (Background Music) ====
          BGM_ENABLE:         "1"     # <— BGM açık
          BGM_SIDECHAIN:      "1"     # 1: ducking açık, 0: düz karışım
          BGM_GAIN_DB:        "-10"   # genel arka plan seviyesi; gerekirse -8 / -6
          BGM_DUCK_THRESH:    "0.03"
          BGM_DUCK_RATIO:     "10"
          BGM_DUCK_ATTACK_MS: "6"
          BGM_DUCK_RELEASE_MS: "180"
          BGM_URLS:           ${{ vars.BGM_URLS }}  # opsiyonel (http linkleri, boşsa bgm/ klasörü taranır)
        run: |
          echo "== ${CHANNEL_NAME} =="
          echo "TOPIC=${TOPIC}"
          echo "LANG=${LANG}"
          echo "SEARCH_TERMS=${SEARCH_TERMS}"
          python autoshorts_daily.py

      - name: Upload artifact (mp4)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.name }}-short
          path: |
            out/**/*.mp4
            out/*.mp4
          if-no-files-found: ignore
          retention-days: 7

      - name: Save global state cache
        if: always()
        uses: actions/cache/save@v4
        with:
          path: |
            state_global.json
            state_global_topics.json
          key: global-state-${{ github.run_id }}

      - name: Save channel state cache
        if: always()
        uses: actions/cache/save@v4
        with:
          path: state_${{ matrix.name }}.json
          key: chstate-${{ matrix.name }}-${{ github.run_id }}
