name: Daily Shorts (all channels)

on:
  schedule:
    - cron: "0 12 * * *"
  workflow_dispatch: {}

permissions:
  contents: read
  actions: read
  checks: read
  id-token: none

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  make-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.build.outputs.matrix }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build matrix from channels.yml
        id: build
        shell: bash
        run: |
          python - <<'PY'
          import yaml, json
          data = yaml.safe_load(open("channels.yml","r",encoding="utf-8"))
          mx = {"include": []}
          for ch in data.get("channels", []):
              mx["include"].append({
                  "name": ch["name"],
                  "env":  ch.get("env", ch["name"]),
                  # MODE artık yönlendirmez, yine de çevresel fallback olarak dursun
                  "mode": ch.get("mode","freeform"),
                  "lang": ch.get("lang","en"),
                  "visibility": ch.get("visibility","public"),
              })
          print(f"matrix={json.dumps(mx)}")
          print(f"::set-output name=matrix::{json.dumps(mx)}")
          PY

  build-upload:
    needs: make-matrix
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix: ${{ fromJSON(needs.make-matrix.outputs.matrix) }}

    environment: ${{ matrix.env }}
    timeout-minutes: 35

    env:
      TZ:                ${{ vars.TZ || 'UTC' }}
      CHANNEL_NAME:      ${{ matrix.name }}
      MODE:              ${{ vars.MODE || matrix.mode }}
      LANG:              ${{ vars.LANG || matrix.lang }}
      VISIBILITY:        ${{ vars.VISIBILITY || matrix.visibility }}
      TTS_VOICE:         ${{ vars.TTS_VOICE || '' }}
      TARGET_MIN_SEC:    ${{ vars.TARGET_MIN_SEC || '22' }}
      TARGET_MAX_SEC:    ${{ vars.TARGET_MAX_SEC || '40' }}
      ROTATION_SEED:     ${{ vars.ROTATION_SEED || '0' }}

      USE_GEMINI:        ${{ vars.USE_GEMINI || '1' }}
      GEMINI_MODEL:      ${{ vars.GEMINI_MODEL || 'gemini-2.5-flash' }}
      UPLOAD_TO_YT:      ${{ vars.UPLOAD_TO_YT || '1' }}

      TOPIC:             ${{ vars.TOPIC || '' }}
      SEARCH_TERMS:      ${{ vars.SEARCH_TERMS || '' }}

      GEMINI_API_KEY:    ${{ secrets.GEMINI_API_KEY }}
      PEXELS_API_KEY:    ${{ secrets.PEXELS_API_KEY }}

      YT_CLIENT_ID:      ${{ secrets.YT_CLIENT_ID }}
      YT_CLIENT_SECRET:  ${{ secrets.YT_CLIENT_SECRET }}
      YT_REFRESH_TOKEN:  ${{ secrets.YT_REFRESH_TOKEN }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Restore global topic memory
        uses: actions/cache/restore@v4
        with:
          path: state_global_topics.json
          key: global-state-v1

      - name: Restore channel state
        uses: actions/cache/restore@v4
        with:
          path: state_${{ env.CHANNEL_NAME }}.json
          key: chstate-${{ env.CHANNEL_NAME }}-v1

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install ffmpeg
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg

      - name: Install deps
        run: |
          python -V
          pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Prepare output dir
        run: mkdir -p out

      - name: Run generator & upload
        run: python autoshorts_daily.py

      - name: Save video artifact
        if: ${{ always() && hashFiles('out/*.mp4') != '' }}
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.CHANNEL_NAME }}-last-video
          path: out/*.mp4
          retention-days: 2
          if-no-files-found: ignore

      - name: Save states back
        if: ${{ always() }}
        uses: actions/cache/save@v4
        with:
          path: |
            state_global_topics.json
            state_${{ env.CHANNEL_NAME }}.json
          key: save-${{ github.run_id }}-${{ env.CHANNEL_NAME }}
